### ISSUE TITLE
Definir estilização do código e configurar editor

### ISSUE THREAD

**Issue by brunorockedu** [brunorockedu/to-do#1]
# Decrição

Será feito definição do lint e configuração

# Tarefas

- [x] Instalar  [golangci-lint](https://github.com/golangci/golangci-lint) local, feramenta agregadora de linters
- [x] Habilitar linters , no arquivo da raiz do projeto .golangci.yml

| Nome  | Próposito |
| ------------- | ------------- |
| Revive  | Verificação de estilo de código e boas práticas. Substituto do golint.  |
| Staticcheck  | Detecta bugs sutis, código obsoleto, problemas de performance e mais.  |
| Errcheck | Verifica se erros retornados por funções são tratados corretamente. |
| Unused | Identifica código não utilizado (variáveis, funções, imports, etc.). |
| Cyclop | Analisa a complexidade ciclomática de funções. |
| Govet | Ferramenta padrão do Go para encontrar erros básicos. |
| Ineffassign | Detecta variáveis com valores atribuídos que nunca são usados. |
| Gocritic | Verifica padrões avançados e antipadrões de código. |

```yaml
linters:
  enable:
    - revive
    - staticcheck
    - errcheck
    - unused
    # ....
run:
  timeout: 5m
```
- [x]  Configurar VSCode (setting.json)

```json
"go.lintTool": "golangci-lint",
"go.lintFlags": [
  "--fast"
]
```
- [x] Criar comando no make para executar os linters
- [x] Criar um arquivo go para testar lint

:white_circle: **(Opcinal)** Configurar roles

```yaml
linters:
  enable:
    - revive          # Estilo e boas práticas.
    - staticcheck     # Análise avançada.
    - errcheck        # Tratamento de erros.
    - unused          # Código morto.
    - ineffassign     # Atribuições desnecessárias.
    - cyclop          # Complexidade.
    - govet           # Ferramentas Go padrão.

linters-settings:
  revive:
    config: path/to/revive.toml  # Caminho para o arquivo de configuração do revive (opcional).
    severity: warning            # Altere a severidade das verificações.
  
  staticcheck:
    checks:                      # Ative ou desative verificações específicas.
      - SA1000  # Exemplo: habilite "Invalid regular expression".
      - SA1019  # Exemplo: desabilite "Using deprecated APIs".
      - SA2000  # Alerta sobre fechamento de recursos.

  errcheck:
    ignore:                      # Ignore certas funções.
      - fmt.Fprintf
      - log.Println

  cyclop:
    max-complexity: 10           # Define o limite de complexidade para funções (padrão: 15).

  govet:
    check-shadowing: true        # Habilite a verificação de shadowing.

  unused:
    checks:
      - funcs                    # Habilite/detecte funções não usadas.
      - vars                     # Habilite/detecte variáveis não usadas.
  
  ineffassign:
    enable-all: true             # Habilite a detecção de todas as atribuições desnecessárias.
```
